---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cabotage
  name: cabotage-enrollment-operator-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cabotage-enrollment-operator-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [cabotage.io]
    resources: [cabotageenrollments]
    verbs: [list, watch, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cabotage
  name: cabotage-enrollment-operator-role-namespaced
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [cabotage.io]
    resources: [cabotageenrollments]
    verbs: [list, watch, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cabotage-enrollment-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cabotage-enrollment-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: cabotage-enrollment-operator-account
    namespace: cabotage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: cabotage
  name: cabotage-enrollment-operator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cabotage-enrollment-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: cabotage-enrollment-operator-account
